### PR TITLE
Rename radio_beam to radio-beam in setup.cfg

### PR DESCRIPTION
**Pull request by keflavich**
Solves issue #58

### CODE REVIEW

**Comment by keflavich** [comment]
I changed the repo name

**Comment by astrofrog** [comment]
The failure looks real, I think that importing from PACKAGENAME should be replaced by 'radio_beam' or PACKAGENAME.replace('-', '_')

**Comment by e-koch** [comment]
@keflavich - What else needs to be done here? I get the same travis error in #51

**Comment by keflavich** [comment]
I don't know.  That seems related to the package name change in *this* PR, but... I can't see why.

**Comment by e-koch** [comment]
Can you just give the name as "radio-beam" in `setup.py`, but leave "radio_beam" in `setup.cfg`. That's what we have in spectral-cube.

**Pull request merged**
