### PR TITLE
Fix beam creation from an area

### LINKED ISSUE #90: Can't instantiate a beam object from an area
Creating a beam from an area fails with the following error:

```py
from radio_beam import Beam
from astropy import units as u

a = (1 * u.arcsec)**2
b = Beam(area=a)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/radio_beam/beam.py", line 100, in __new__
    self = super(Beam, cls).__new__(cls, _to_area(major,minor).value, u.sr)
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/radio_beam/beam.py", line 24, in _to_area
    return (major * minor * FWHM_TO_AREA).to(u.sr)
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/quantity.py", line 689, in to
    return self._new_view(self._to_value(unit, equivalencies), unit)
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/quantity.py", line 660, in _to_value
    return self.unit.to(unit, self.view(np.ndarray),
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/core.py", line 987, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/core.py", line 918, in _get_converter
    raise exc
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/core.py", line 903, in _get_converter
    return self._apply_equivalencies(
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/core.py", line 886, in _apply_equivalencies
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'arcsec2 deg4' and 'sr' (solid angle) are not convertible
```

I'm using radio_beam 0.3.2.

### PR DESCRIPTION
**Pull request by smaret**
Closes #90.

### CODE REVIEW

**Review by keflavich — APPROVED** [review]
@e-koch want to have a look at this?  I think the change is fine, but maybe we should force `area.to(u.deg**2)` ?  or `rad = sqrt(area).to(u.deg)` ?

**Comment by smaret** [comment]
> but maybe we should force `area.to(u.deg**2)` ? or `rad = sqrt(area).to(u.deg)` ?

The units of `major` and `minor` are not forced to `u.deg` when creating a beam from these parameters, so I don't think that we need to force `area` units neither.  We may want to check wether `area` units are equivalent to `u.deg**2` though.

**Comment by e-koch** [comment]
Agreed @smaret -- A check for an area equiv. unit makes sense. thanks!

**Comment by e-koch** [comment]
The major/minor do get checked for the unit type. This check would just be for an easier to understand error message

**Comment by smaret** [comment]
> The major/minor do get checked for the unit type

Here you mean ? https://github.com/radio-astro-tools/radio-beam/blob/ee8ed32ce3376a136ef1048746a9ab55dfd8cbb3/radio_beam/beam.py#L73-L77

**Comment by smaret** [comment]
The test is weird. If one provides `major` with an invalid unit, it is multiplied by `u.deg` and a warning message saying that degrees are assumed is displayed.  But later one a `UnitConversionError` is thrown.

**Comment by smaret** [comment]
Perhaps the last line should read:
```
major = major.value * u.deg
```
But that's a separate issue.

**Comment by e-koch** [comment]
> Perhaps the last line should read:
> 
> ```python
> major = major.value * u.deg
> ```
> 
> But that's a separate issue.

Agreed. I'll make a new issue. I think it was to allow non Quantities, but we should really remove it for consistency.

**Review by e-koch — APPROVED** [review]

**Pull request merged**
