### PR TITLE
Swap major and minor axes if they're wrong

### PR DESCRIPTION
**Pull request by keflavich**
if minor > major, they should be swapped (on reading)

### CODE REVIEW

**Comment by keflavich** [comment]
If the user mis-specifies major and minor, they'll be swapped.  Is there any risk that this causes trouble for users because they flipped the definition of the PA too?  Or is the warning enough?

**Comment by e-koch** [comment]
I think we should adjust PA by 180 deg whenever this occurs as a default, and then have the warning state that the PA is adjusted. That way we're consistently transforming from the original inputs.

**Comment by keflavich** [comment]
you mean 90 deg?

**Comment by keflavich** [comment]
hm, maybe we should just raise an exception then..... I'm not convinced there's a clear default in this case.

**Comment by e-koch** [comment]
I definitely mean 90 deg.

**Comment by e-koch** [comment]
The exception seems reasonable to me. I'm imagining the case where a few highly elongated beams (that maybe you would mask out, anyways, but) end up giving weird convolution products if the PA is off by 90 deg.

**Comment by e-koch** [comment]
Otherwise, LGTM.

**Pull request merged**
