### PR TITLE
Update package infrastructure following APE17

### PR DESCRIPTION
**Pull request by e-koch**
Follows @astrofrog's changes for spectral-cube (https://github.com/radio-astro-tools/spectral-cube/pull/599). Needed for tests to eventually pass in #81.

### CODE REVIEW

**Comment by e-koch** [comment]
My infrastructure knowledge is weak, too. @astrofrog, would you mind reviewing to make sure I didn't miss something?

**Comment by astrofrog** [comment]
I can review tomorrow!

**Comment by e-koch** [comment]
@astrofrog I'm finally coming back to this. Would you mind having a look through?

**Comment by e-koch** [comment]
Tests still pass and I don't see any bigger issues. I'm going to merge to push #81 ahead and address any smaller infrastructure issues in another PR.

**Pull request merged**
